#!/bin/bash

rm -rf build/
rm -fr jni/.deps
rm -fr jni/.libs

rm -f bench_inv
rm -f bench_ecdh
rm -f bench_ecmult
rm -f bench_sign
rm -f bench_verify
rm -f bench_schnorr_verify
rm -f bench_recover
rm -f bench_internal
rm -f tests
rm -f exhaustive_tests
rm -f gen_context
rm -f *.exe
rm -f *.a
rm -f !.gitignore
rm -f .DS_Store

rm -f Makefile
rm -f configure
rm -fr .libs/
rm -f Makefile.in
rm -f aclocal.m4
rm -fr autom4te.cache/
rm -f config.log
rm -f config.status
rm -f *.tar.gz
rm -f *.la
rm -f libtool
rm -fr .deps/
rm -f .dirstamp
rm -f *.lo
rm -f *.o
rm -f src/libsecp256k1-config.h
rm -f src/libsecp256k1-config.h.in
rm -f src/ecmult_static_context.h
rm -f build-aux/config.guess
rm -f build-aux/config.sub
rm -f build-aux/depcomp
rm -f build-aux/install-sh
rm -f build-aux/ltmain.sh
rm -f build-aux/m4/libtool.m4
rm -f build-aux/m4/lt~obsolete.m4
rm -f build-aux/m4/ltoptions.m4
rm -f build-aux/m4/ltsugar.m4
rm -f build-aux/m4/ltversion.m4
rm -f build-aux/missing
rm -f build-aux/compile
rm -f build-aux/test-driver
rm -f src/stamp-h1
rm -f libsecp256k1.pc
rm -f target/
